# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "bazil.org/fuse"

[[constraint]]
  branch = "master"
  name = "github.com/cespare/cp"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.5.4"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.0.0"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  branch = "v0.1.1"
  name = "gopkg.in/fatih/set.v0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/karalabe/cookiejar.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/natefinch/npipe.v2"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"
